export type Broker = {
  id: string;
  name: string;
  instruments: string;
  avgUserProfile: string;
  accountTypes: string;
  minDeposit: string;
  minSpreadEURUSD: string;
  commissionsForexUSD: string;
  leverage: string;
  regulationLatam: string;
  platforms: string;
  education: string;
  copyTrading: string;
  liquidityModel: string;
  ibOfferings: string;
  welcomeBonus: string;
  promoInfo: string;
  referrals: string;
  trustpilot: string;
};

// TODO: move BROKERS to Supabase (tabla brokers) + endpoint RLS read-only
export const BROKERS: Broker[] = [
  {
    id: "acy",
    name: "ACY",
    instruments: "+2500 CFDs",
    avgUserProfile: "High Transactions level; High Risk Tolerance & Mgmt; Very Active / Pro-Traders",
    accountTypes: "Basic / Standard / proZero",
    minDeposit: "USD 50 / 100 / 200",
    minSpreadEURUSD: "1 / 0 / 0",
    commissionsForexUSD: "0 / 0 / 6",
    leverage: "1:5000",
    regulationLatam: "SVG FSA",
    platforms: "Metatrader 4 & 5",
    education: "Medium structured Course; Market Analysis / Demo**",
    copyTrading: "Trading Cup",
    liquidityModel: "STP (mainly) / ECN",
    ibOfferings: "Lot 15 USD",
    welcomeBonus: "30% 1st Deposit Until 1000 USD; 10% After",
    promoInfo: "Spin & Win / Free VPS / Free Capitalise IA",
    referrals: "N/A",
    trustpilot: "4.7 (676)"
  },
  {
    id: "vantage",
    name: "Vantage",
    instruments: "+1000 CFDs",
    avgUserProfile: "High Transactions level; High Risk Tolerance & Mgmt; Very Active / Pro-Traders",
    accountTypes: "Standard / Raw  / Pro",
    minDeposit: "50 / 50 / 10000",
    minSpreadEURUSD: "1 / 0 / 0",
    commissionsForexUSD: "0 / 6 / 3",
    leverage: "1:500",
    regulationLatam: "(VFSC - Vanuatu) - Low",
    platforms: "Metatrader 4 & 5",
    education: "No structured Course; Market Analysis / Demo**",
    copyTrading: "Vantage Copy + Providers",
    liquidityModel: "ECN & STP",
    ibOfferings: "8 USD (0,35 Pips) - 3.5 USD s",
    welcomeBonus: "150% 1st Deposit Until 1000 USD; Prom 83% After",
    promoInfo: "Free VPS",
    referrals: "250 USD",
    trustpilot: "4.5 (9124)"
  },
  {
    id: "avatrade",
    name: "Ava Trade",
    instruments: "+1000 CFDs",
    avgUserProfile: "Low/Mid Transactions; Mid Risk Tolerance; Beginners & Active Traders",
    accountTypes: "Operador / VIP",
    minDeposit: "200 / 10000",
    minSpreadEURUSD: "1 / 0.8",
    commissionsForexUSD: "0",
    leverage: "1:400",
    regulationLatam: "(BVI - Virgin Islands) - Medium",
    platforms: "Metatrader 4 & 5",
    education: "No structured Course; Market Analysis / Demo**",
    copyTrading: "Dupli Trade",
    liquidityModel: "Market Maker",
    ibOfferings: "0,35 Pips -  3.3 USD",
    welcomeBonus: "100% 1st Deposit Until 1000 USD",
    promoInfo: "N/A",
    referrals: "50-250 USD",
    trustpilot: "4.8 (10717)"
  },
  {
    id: "xm",
    name: "XM",
    instruments: "+1000 CFDs",
    avgUserProfile: "Low/Mid Transactions; Mid Risk Tolerance; Beginners & Active Traders",
    accountTypes: "Standard / Ultra Low / Shares",
    minDeposit: "5 / 5 / 10000",
    minSpreadEURUSD: "1.6 / 0.7 / 0",
    commissionsForexUSD: "0 / 0 / 7",
    leverage: "1:1000",
    regulationLatam: "(FSA SEY) - Low",
    platforms: "XM App; Metatrader 4 & 5",
    education: "No structured Course; Market Analysis / Demo**",
    copyTrading: "XM CopyTrading",
    liquidityModel: "Market Maker (Mainly) / ECN",
    ibOfferings: "0",
    welcomeBonus: "100% 1st Deposit Until 500 USD; Prom 10% After; 30 usd",
    promoInfo: "30 usd No deposit bonus",
    referrals: "80 USD",
    trustpilot: "3.9 (2586)"
  },
  {
    id: "tickmill",
    name: "Tickmill",
    instruments: "+300 CFDs",
    avgUserProfile: "High Transactions level; High Risk Tolerance & Mgmt; Very Active / Pro-Traders",
    accountTypes: "Classic / Pro / VIP",
    minDeposit: "100 / 100 / 50000",
    minSpreadEURUSD: "1.6 / 0 / 0",
    commissionsForexUSD: "0 / 4 / 2",
    leverage: "1:1000",
    regulationLatam: "(FSA SEY) - Low",
    platforms: "TraddingView; Metatrader 4 & 5",
    education: "No structured Course; Market Analysis / Demo**",
    copyTrading: "No",
    liquidityModel: "ECN & STP",
    ibOfferings: "6 USD / 30 USD",
    welcomeBonus: "100% 1st Deposit Until 10000 USD (Max 10000 USD in Bonus)",
    promoInfo: "Predict the NFP figure and win $500!",
    referrals: "N/A",
    trustpilot: "4.1 (1090)"
  },
  {
    id: "exness",
    name: "Exness",
    instruments: "+270 CFDs",
    avgUserProfile: "Mid / High Transactions level; Mid / High Risk Tolerance; Active / Pro-Traders",
    accountTypes: "Standard / Pro / Zero / Invest / Trade CFD",
    minDeposit: "10 / 200 / 200",
    minSpreadEURUSD: "0.9 / 0.6 / 0",
    commissionsForexUSD: "0 / 0 / 7",
    leverage: "1:Unlimited",
    regulationLatam: "(FSA SEY) - Low",
    platforms: "Exness; Metatrader 4 & 5",
    education: "Medium structured Course; Market Analysis / Demo*; Cents Account",
    copyTrading: "Exness Social",
    liquidityModel: "Market Maker & NDD",
    ibOfferings: "53% Spread FX",
    welcomeBonus: "N/A",
    promoInfo: "Swap Free",
    referrals: "N/A",
    trustpilot: "4.8 (21699)"
  },
  {
    id: "libertex",
    name: "Libertex",
    instruments: "+692",
    avgUserProfile: "High Transactions level; High Risk Tolerance & Mgmt; Very Active / Pro-Traders",
    accountTypes: "Standard / Raw",
    minDeposit: "0 / 10",
    minSpreadEURUSD: "N/A / 0.1",
    commissionsForexUSD: "0 / 6",
    leverage: "1:1000",
    regulationLatam: "FSCA (S África) Medium",
    platforms: "Libertex; MT4 & MT5",
    education: "No structured Course; Demo***",
    copyTrading: "No Social Trading",
    liquidityModel: "Market Maker",
    ibOfferings: "0 / 6",
    welcomeBonus: "100% 1st Deposit Until 500 USD",
    promoInfo: "10% of Paid Comissions",
    referrals: "N/A",
    trustpilot: "3.8 (3583)"
  },
  {
    id: "fp-markets",
    name: "FP Markets",
    instruments: "1200 CFDs",
    avgUserProfile: "High Transactions level; High Risk Tolerance & Mgmt; Very Active / Pro-Traders",
    accountTypes: "Standard / Razor",
    minDeposit: "100",
    minSpreadEURUSD: "1.2 / 0.1",
    commissionsForexUSD: "0 / 6",
    leverage: "1:500",
    regulationLatam: "SCB (Bahamas) Low",
    platforms: "Mobile App; MT4 & MT5; C-Trader /Trading View",
    education: "Medium structured Course; Market Analysis / Demo*",
    copyTrading: "CopyTrading",
    liquidityModel: "STP (mainly) / ECN",
    ibOfferings: "0 / 6",
    welcomeBonus: "N/A",
    promoInfo: "N/A",
    referrals: "N/A",
    trustpilot: "4.9 (9172)"
  },
  {
    id: "pepperstone",
    name: "Pepperstone",
    instruments: "1444 CFDs",
    avgUserProfile: "High Transactions level; High Risk Tolerance & Mgmt; Very Active / Pro-Traders",
    accountTypes: "Standard / Pro",
    minDeposit: "13",
    minSpreadEURUSD: "0.1 / 1",
    commissionsForexUSD: "0 / 7",
    leverage: "1:500",
    regulationLatam: "FSCA (Sudáfrica)",
    platforms: "MT4 & MT5",
    education: "Low structured Course; Market Analysis / Demo**",
    copyTrading: "CopyTrading",
    liquidityModel: "STP (mainly) / ECN",
    ibOfferings: "0 / 7",
    welcomeBonus: "500 USD Until",
    promoInfo: "Cash Back Per Volume",
    referrals: "N/A",
    trustpilot: "4.5 (3097)"
  },
  {
    id: "hfm",
    name: "HFM",
    instruments: "1000 CFDs",
    avgUserProfile: "Mid / High Transactions level; Mid / High Risk Tolerance; Active / Pro-Traders",
    accountTypes: "Zero / Pro",
    minDeposit: "5",
    minSpreadEURUSD: "0 / 0.6",
    commissionsForexUSD: "1.5 / 0.8 / 0.1",
    leverage: "1:2000",
    regulationLatam: "VFSC (Vanuatu) - Vanuatú",
    platforms: "HFM (mobile); MT4 & MT5",
    education: "\"Medium structured Course; Market Analysis / Demo**\"",
    copyTrading: "Copy Trading",
    liquidityModel: "Market Maker / STP & ECN",
    ibOfferings: "0",
    welcomeBonus: "100% 1st Deposit Until 500 USD",
    promoInfo: "Swap Free",
    referrals: "200",
    trustpilot: "4.6 (2296)"
  },
  {
    id: "multibank",
    name: "MultiBank",
    instruments: "20000 CFDs",
    avgUserProfile: "Low/Mid Transactions; Mid Risk Tolerance; Beginners & Active Traders",
    accountTypes: "Standard / Pro / ECN",
    minDeposit: "50 / 1000 / 10000",
    minSpreadEURUSD: "0",
    commissionsForexUSD: "0 / 0 / 4",
    leverage: "1:500",
    regulationLatam: "(IFSC - Belice) - Medium",
    platforms: "MultiBank Plus; MT4 & MT5",
    education: "\"Medium structured Course; Market Analysis / Demo**\"",
    copyTrading: "Copy Trading",
    liquidityModel: "Market Maker / ECN",
    ibOfferings: "N/A",
    welcomeBonus: "100% Each Deposit of 200",
    promoInfo: "Spinn Continuos",
    referrals: "N/A",
    trustpilot: "4.6 (1472)"
  },
  {
    id: "roboforex",
    name: "Roboforex",
    instruments: "+12000",
    avgUserProfile: "Mid / High Transactions level; Mid / High Risk Tolerance; Active / Pro-Traders / Index Traders",
    accountTypes: "Prime / Pro / ECN",
    minDeposit: "10 / 10 / 10",
    minSpreadEURUSD: "0.1 / 1.3 / 0.1",
    commissionsForexUSD: "0 / 0 / 4",
    leverage: "1:2000",
    regulationLatam: "FSC (Mauricio) Low",
    platforms: "RB Mobile App; MT4 & MT5",
    education: "Cent Accounts; Market Analysis / Demo**",
    copyTrading: "Copy Trading",
    liquidityModel: "Market Maker / STP & ECN",
    ibOfferings: "0",
    welcomeBonus: "50% Until deposit of 20000",
    promoInfo: "Deposit Bonus",
    referrals: "10% of Partners Comissions",
    trustpilot: "2.6 (633)"
  },
  {
    id: "weltrade",
    name: "Weltrade",
    instruments: "100 CFDs",
    avgUserProfile: "High Transactions level; High Risk Tolerance & Mgmt; Very Active / Pro-Traders",
    accountTypes: "Micro  / Pro / SintX",
    minDeposit: "1 / 100 / 1",
    minSpreadEURUSD: "2.3 / 0.9",
    commissionsForexUSD: "0 / 0 / 0",
    leverage: "1:1000 / 1:10000 (SintX)",
    regulationLatam: "(BVI - Virgin Islands) - Medium",
    platforms: "Weltrade App; MT4 & MT5; BlackArrow",
    education: "\"Medium structured Course; Market Analysis / Demo**\"",
    copyTrading: "Social / Copy Trading",
    liquidityModel: "Market Maker / STP & ECN",
    ibOfferings: "0",
    welcomeBonus: "0",
    promoInfo: "0",
    referrals: "20 USD",
    trustpilot: "4.6 (1658)"
  },
  {
    id: "zero-markets",
    name: "Zero Markets",
    instruments: "+680",
    avgUserProfile: "Low/Mid Transactions; Mid Risk Tolerance; Beginners & Active Traders",
    accountTypes: "Estándar / Super Zero",
    minDeposit: "30",
    minSpreadEURUSD: "10 / \"0\"",
    commissionsForexUSD: "0 / 5",
    leverage: "1:500",
    regulationLatam: "FSCA (S África) Medium",
    platforms: "WebTrader (own); xStation (own); Metatrader 4",
    education: "Structured Course; Market Analysis / Demo*",
    copyTrading: "Copy Trading",
    liquidityModel: "Market Maker",
    ibOfferings: "N/A",
    welcomeBonus: "0",
    promoInfo: "0",
    referrals: "Multilevel Referrals",
    trustpilot: "4.9 (1000)"
  },
  {
    id: "etoro",
    name: "eToro",
    instruments: "+7,000",
    avgUserProfile: "Mid / High Transactions level; Mid / High Risk Tolerance; Active / Pro-Traders",
    accountTypes: "Retail Client /  eToro Club",
    minDeposit: "200",
    minSpreadEURUSD: "1 / 1",
    commissionsForexUSD: "1 / 7",
    leverage: "1:30",
    regulationLatam: "(BVI - Virgin Islands) - Medium",
    platforms: "CopyTrader (Leader)",
    education: "Medium structured Course; Market Analysis / Demo*",
    copyTrading: "CopyTrader (Leader)",
    liquidityModel: "Market Maker & NDD",
    ibOfferings: "N/A",
    welcomeBonus: "0",
    promoInfo: "0",
    referrals: "0",
    trustpilot: "4.2 (28442)"
  },
  {
    id: "xtb",
    name: "XTB",
    instruments: "+5,800",
    avgUserProfile: "Mid / High Transactions level; Mid / High Risk Tolerance; Active / Pro-Traders",
    accountTypes: "Standard /  Pro Account",
    minDeposit: "0",
    minSpreadEURUSD: "0.9 / 0.1",
    commissionsForexUSD: "1 / 7",
    leverage: "1:500",
    regulationLatam: "(IFSC - Belice) - Medium",
    platforms: "xStation (own)",
    education: "Full structured Course; Market Analysis / Demo*",
    copyTrading: "No",
    liquidityModel: "Market Maker & NDD",
    ibOfferings: "0",
    welcomeBonus: "0",
    promoInfo: "0",
    referrals: "0",
    trustpilot: "4.0 (2083)"
  }
];
    education: "No structured Course; Market Analysis / Demo**",
    copyTrading: "No",
    liquidityModel: "ECN & STP",
    ibOfferings: "6 USD / 30 USD",
    welcomeBonus: "100% 1st Deposit Until 10000 USD (Max 10000 USD in Bonus)",
    promoInfo: "Predict the NFP figure and win $500!",
    referrals: "N/A",
    trustpilot: "4.1 (1090)"
  },
  {
    id: "exness",
    name: "Exness",
    instruments: "+270 CFDs",
    avgUserProfile: "Mid / High Transactions level; Mid / High Risk Tolerance; Active / Pro-Traders",
    accountTypes: "Standard / Pro / Zero / Invest / Trade CFD",
    minDeposit: "10 / 200 / 200",
    minSpreadEURUSD: "0.9 / 0.6 / 0",
    commissionsForexUSD: "0 / 0 / 7",
    leverage: "1:Unlimited",
    regulationLatam: "(FSA SEY) - Low",
    platforms: "Exness; Metatrader 4 & 5",
    education: "Medium structured Course; Market Analysis / Demo*; Cents Account",
    copyTrading: "Exness Social",
    liquidityModel: "Market Maker & NDD",
    ibOfferings: "53% Spread FX",
    welcomeBonus: "N/A",
    promoInfo: "Swap Free",
    referrals: "N/A",
    trustpilot: "4.8 (21699)"
  },
  {
    id: "libertex",
    name: "Libertex",
    instruments: "+692",
    avgUserProfile: "High Transactions level; High Risk Tolerance & Mgmt; Very Active / Pro-Traders",
    accountTypes: "Standard / Raw",
    minDeposit: "0 / 10",
    minSpreadEURUSD: "N/A / 0.1",
    commissionsForexUSD: "0 / 6",
    leverage: "1:1000",
    regulationLatam: "FSCA (S África) Medium",
    platforms: "Libertex; MT4 & MT5",
    education: "No structured Course; Demo***",
    copyTrading: "No Social Trading",
    liquidityModel: "Market Maker",
    ibOfferings: "0 / 6",
    welcomeBonus: "100% 1st Deposit Until 500 USD",
    promoInfo: "10% of Paid Comissions",
    referrals: "N/A",
    trustpilot: "3.8 (3583)"
  },
  {
    id: "fp-markets",
    name: "FP Markets",
    instruments: "1200 CFDs",
    avgUserProfile: "High Transactions level; High Risk Tolerance & Mgmt; Very Active / Pro-Traders",
    accountTypes: "Standard / Razor",
    minDeposit: "100",
    minSpreadEURUSD: "1.2 / 0.1",
    commissionsForexUSD: "0 / 6",
    leverage: "1:500",
    regulationLatam: "SCB (Bahamas) Low",
    platforms: "Mobile App; MT4 & MT5; C-Trader /Trading View",
    education: "Medium structured Course; Market Analysis / Demo*",
    copyTrading: "CopyTrading",
    liquidityModel: "STP (mainly) / ECN",
    ibOfferings: "0 / 6",
    welcomeBonus: "N/A",
    promoInfo: "N/A",
    referrals: "N/A",
    trustpilot: "4.9 (9172)"
  },
  {
    id: "pepperstone",
    name: "Pepperstone",
    instruments: "1444 CFDs",
    avgUserProfile: "High Transactions level; High Risk Tolerance & Mgmt; Very Active / Pro-Traders",
    accountTypes: "Standard / Pro",
    minDeposit: "13",
    minSpreadEURUSD: "0.1 / 1",
    commissionsForexUSD: "0 / 7",
    leverage: "1:500",
    regulationLatam: "FSCA (Sudáfrica)",
    platforms: "MT4 & MT5",
    education: "Low structured Course; Market Analysis / Demo**",
    copyTrading: "CopyTrading",
    liquidityModel: "STP (mainly) / ECN",
    ibOfferings: "0 / 7",
    welcomeBonus: "500 USD Until",
    promoInfo: "Cash Back Per Volume",
    referrals: "N/A",
    trustpilot: "4.5 (3097)"
  },
  {
    id: "hfm",
    name: "HFM",
    instruments: "1000 CFDs",
    avgUserProfile: "Mid / High Transactions level; Mid / High Risk Tolerance; Active / Pro-Traders",
    accountTypes: "Zero / Pro",
    minDeposit: "5",
    minSpreadEURUSD: "0 / 0.6",
    commissionsForexUSD: "1.5 / 0.8 / 0.1",
    leverage: "1:2000",
    regulationLatam: "VFSC (Vanuatu) - Vanuatú",
    platforms: "HFM (mobile); MT4 & MT5",
    education: "\"Medium structured Course; Market Analysis / Demo**\"",
    copyTrading: "Copy Trading",
    liquidityModel: "Market Maker / STP & ECN",
    ibOfferings: "0",
    welcomeBonus: "100% 1st Deposit Until 500 USD",
    promoInfo: "Swap Free",
    referrals: "200",
    trustpilot: "4.6 (2296)"
  },
  {
    id: "multibank",
    name: "MultiBank",
    instruments: "20000 CFDs",
    avgUserProfile: "Low/Mid Transactions; Mid Risk Tolerance; Beginners & Active Traders",
    accountTypes: "Standard / Pro / ECN",
    minDeposit: "50 / 1000 / 10000",
    minSpreadEURUSD: "0",
    commissionsForexUSD: "0 / 0 / 4",
    leverage: "1:500",
    regulationLatam: "(IFSC - Belice) - Medium",
    platforms: "MultiBank Plus; MT4 & MT5",
    education: "\"Medium structured Course; Market Analysis / Demo**\"",
    copyTrading: "Copy Trading",
    liquidityModel: "Market Maker / ECN",
    ibOfferings: "N/A",
    welcomeBonus: "100% Each Deposit of 200",
    promoInfo: "Spinn Continuos",
    referrals: "N/A",
    trustpilot: "4.6 (1472)"
  },
  {
    id: "roboforex",
    name: "Roboforex",
    instruments: "+12000",
    avgUserProfile: "Mid / High Transactions level; Mid / High Risk Tolerance; Active / Pro-Traders / Index Traders",
    accountTypes: "Prime / Pro / ECN",
    minDeposit: "10 / 10 / 10",
    minSpreadEURUSD: "0.1 / 1.3 / 0.1",
    commissionsForexUSD: "0 / 0 / 4",
    leverage: "1:2000",
    regulationLatam: "FSC (Mauricio) Low",
    platforms: "RB Mobile App; MT4 & MT5",
    education: "Cent Accounts; Market Analysis / Demo**",
    copyTrading: "Copy Trading",
    liquidityModel: "Market Maker / STP & ECN",
    ibOfferings: "0",
    welcomeBonus: "50% Until deposit of 20000",
    promoInfo: "Deposit Bonus",
    referrals: "10% of Partners Comissions",
    trustpilot: "2.6 (633)"
  },
  {
    id: "weltrade",
    name: "Weltrade",
    instruments: "100 CFDs",
    avgUserProfile: "High Transactions level; High Risk Tolerance & Mgmt; Very Active / Pro-Traders",
    accountTypes: "Micro  / Pro / SintX",
    minDeposit: "1 / 100 / 1",
    minSpreadEURUSD: "2.3 / 0.9",
    commissionsForexUSD: "0 / 0 / 0",
    leverage: "1:1000 / 1:10000 (SintX)",
    regulationLatam: "(BVI - Virgin Islands) - Medium",
    platforms: "Weltrade App; MT4 & MT5; BlackArrow",
    education: "\"Medium structured Course; Market Analysis / Demo**\"",
    copyTrading: "Social / Copy Trading",
    liquidityModel: "Market Maker / STP & ECN",
    ibOfferings: "0",
    welcomeBonus: "0",
    promoInfo: "0",
    referrals: "20 USD",
    trustpilot: "4.6 (1658)"
  },
  {
    id: "zero-markets",
    name: "Zero Markets",
    instruments: "+680",
    avgUserProfile: "Low/Mid Transactions; Mid Risk Tolerance; Beginners & Active Traders",
    accountTypes: "Estándar / Super Zero",
    minDeposit: "30",
    minSpreadEURUSD: "10 / \"0\"",
    commissionsForexUSD: "0 / 5",
    leverage: "1:500",
    regulationLatam: "FSCA (S África) Medium",
    platforms: "WebTrader (own); xStation (own); Metatrader 4",
    education: "Structured Course; Market Analysis / Demo*",
    copyTrading: "Copy Trading",
    liquidityModel: "Market Maker",
    ibOfferings: "N/A",
    welcomeBonus: "0",
    promoInfo: "0",
    referrals: "Multilevel Referrals",
    trustpilot: "4.9 (1000)"
  },
  {
    id: "etoro",
    name: "eToro",
    instruments: "+7,000",
    avgUserProfile: "Mid / High Transactions level; Mid / High Risk Tolerance; Active / Pro-Traders",
    accountTypes: "Retail Client /  eToro Club",
    minDeposit: "200",
    minSpreadEURUSD: "1 / 1",
    commissionsForexUSD: "1 / 7",
    leverage: "1:30",
    regulationLatam: "(BVI - Virgin Islands) - Medium",
    platforms: "CopyTrader (Leader)",
    education: "Medium structured Course; Market Analysis / Demo*",
    copyTrading: "CopyTrader (Leader)",
    liquidityModel: "Market Maker & NDD",
    ibOfferings: "N/A",
    welcomeBonus: "0",
    promoInfo: "0",
    referrals: "0",
    trustpilot: "4.2 (28442)"
  },
  {
    id: "xtb",
    name: "XTB",
    instruments: "+5,800",
    avgUserProfile: "Mid / High Transactions level; Mid / High Risk Tolerance; Active / Pro-Traders",
    accountTypes: "Standard /  Pro Account",
    minDeposit: "0",
    minSpreadEURUSD: "0.9 / 0.1",
    commissionsForexUSD: "1 / 7",
    leverage: "1:500",
    regulationLatam: "(IFSC - Belice) - Medium",
    platforms: "xStation (own)",
    education: "Full structured Course; Market Analysis / Demo*",
    copyTrading: "No",
    liquidityModel: "Market Maker & NDD",
    ibOfferings: "0",
    welcomeBonus: "0",
    promoInfo: "0",
    referrals: "0",
    trustpilot: "4.0 (2083)"
  }
];
